---
title: "Week 10: Additional Practice - Building AI Collaboration Skills"
subtitle: "CSC101 Introduction to Programming"
author: "Your Name"
date: "September 2026"
format:
  html:
    toc: true
    toc-expand: 2
    code-fold: false
    embed-resources: true
---

# 🎯 Building Confidence with AI-Assisted Data Analysis

This notebook provides additional practice exercises to strengthen your AI collaboration skills and build confidence with business data processing. Use these exercises to deepen your understanding before or after the main workshop.

**Remember**: The goal isn't to memorize pandas syntax - it's to become effective at directing AI to solve business problems.

---

# Exercise Set 1: Sales Data Analysis 📊

## Business Context

You're working as a Business Analyst for an office supply company. Your manager has given you sales data and asked for insights to help plan next quarter's inventory and sales strategy.

## Data Overview

We'll use the `sales_data.csv` file with columns:
- **Date**: Sale date
- **Product**: Product name
- **Quantity**: Units sold
- **Unit_Price**: Price per unit (with $ signs)
- **Total_Sale**: Total transaction value
- **Sales_Rep**: Employee who made the sale
- **Region**: Geographic region

In [ ]:
import pandas as pd

# Load the sales data
sales_df = pd.read_csv('/content/sales_data.csv')

# Display first few rows
print("📋 Sales Data Sample:")
print("=" * 40)
print(sales_df.head())
print(f"\nDataset: {len(sales_df)} transactions across {sales_df['Region'].nunique()} regions")

📋 Sales Data Sample:
========================================
         Date                      Product Quantity Unit_Price Total_Sale  \
0  2024-08-01  Business Analytics Software       $2   $2499.00   $4998.00
1  2024-08-01     Office Chair - Ergonomic      $15    $299.50   $4492.50
2  2024-08-02                Standing Desk       $8    $599.00   $4792.00
3  2024-08-02      Laptop - Business Grade      $12   $1899.00  $22788.00
4  2024-08-03             Conference Table       $3   $1250.00   $3750.00

       Sales_Rep Region
0     Sarah Chen    NSW
1   Michael Wong    VIC
2  Emma Thompson    QLD
3    David Kumar    NSW
4      Lisa Park     WA

Dataset: 20 transactions across 4 regions

## Practice Exercise 1.1: Sales Performance by Region

::: {.callout-tip}
## Your AI Collaboration Challenge

**Business Question**: "Which region is performing best, and what's the average sale size by region?"

**Your Task**: Practice prompting AI with this business context. Try creating a prompt that asks for:
1. Total sales by region
2. Average sale amount by region  
3. Number of transactions by region
4. Results formatted for a manager presentation

**Write your prompt below, then see what AI generates:**
:::

**Your Prompt:**
```
Using the sales_df DataFrame, calculate total sales, average sale amount, and number of transactions for each region. Sort the results by total sales from highest to lowest. Explain the results in simple language for a manager. Please provide simple pandas code and explain each step.
```

**AI Response:**
# Convert Total_Sale to numbers, removing dollar signs and commas
sales_df["Total_Sale"] = pd.to_numeric(
    sales_df["Total_Sale"]
    .astype(str)
    .str.replace("$", "", regex=False)
    .str.replace(",", "", regex=False),
    errors="coerce"
)

# Summarise sales performance by region
region_summary = (
    sales_df.groupby("Region")
    .agg(
        Total_Sales=("Total_Sale", "sum"),
        Average_Sale=("Total_Sale", "mean"),
        Transactions=("Total_Sale", "count")
    )
    .sort_values("Total_Sales", ascending=False)
    .round(2)
)

display(region_summary)

In [6]:
# Paste AI-generated code here and run it

# Convert Total_Sale to numbers, removing dollar signs and commas
sales_df["Total_Sale"] = pd.to_numeric(
    sales_df["Total_Sale"]
    .astype(str)
    .str.replace("$", "", regex=False)
    .str.replace(",", "", regex=False),
    errors="coerce"
)

# Summarise sales performance by region
region_summary = (
    sales_df.groupby("Region")
    .agg(
        Total_Sales=("Total_Sale", "sum"),
        Average_Sale=("Total_Sale", "mean"),
        Transactions=("Total_Sale", "count")
    )
    .sort_values("Total_Sales", ascending=False)
    .round(2)
)

display(region_summary)

# Remember to critique and improve if needed!

        Total_Sales  Average_Sale  Transactions
Region
NSW        50902.75       6362.84             8
VIC        21085.50       5271.38             4
QLD        11904.30       2976.08             4
WA         10049.25       2512.31             4

**Your Critique:**
- What did AI do well?
- What would you ask AI to improve?
- Does the output help answer the business question?

AI did well by calculating total sales, average sale amount, and the number of transactions for each region. It sorted the regions from highest to lowest total sales, which made the results easy to compare. NSW had the highest total sales, at 50,902.75, and the most transactions, with 8. Its average sale amount was also the highest, at 6,362.84. WA had the lowest total sales, at 10,049.25, and the lowest average sale amount, at 2,512.31.

The output helps answer which region performed best. To improve it, I could ask AI to explain whether the differences were mainly due to the number of transactions or the average sale amount, and to suggest actions for the lower-performing regions.

---

## Practice Exercise 1.2: Top Performing Products

::: {.callout-tip}
## Business Scenario

Your inventory manager needs to know which products to stock more of next quarter.

**Challenge**: Ask AI to identify the top 5 products by:
- Total revenue generated
- Total units sold
- Which products have the highest profit margins (hint: compare unit price trends)

**Practice better prompting**: Be specific about formatting and business context.
:::

**Your Prompt:**
```
[Using the sales_df DataFrame, identify the top-performing products by total sales. Calculate total sales, average sale amount, and number of transactions for each product. Sort the results by total sales from highest to lowest, and explain the results in simple language for a manager. Please provide simple pandas code and explain each step.]
```

**AI Response:**
# Convert Total_Sale to numbers
sales_df["Total_Sale"] = pd.to_numeric(
    sales_df["Total_Sale"]
    .astype(str)
    .str.replace("$", "", regex=False)
    .str.replace(",", "", regex=False),
    errors="coerce"
)

# Summarise sales performance by product
product_summary = (
    sales_df.groupby("Product")
    .agg(
        Total_Sales=("Total_Sale", "sum"),
        Average_Sale=("Total_Sale", "mean"),
        Transactions=("Total_Sale", "count")
    )
    .sort_values("Total_Sales", ascending=False)
    .round(2)
)

display(product_summary)

In [7]:
# AI-generated code goes here
# Convert Total_Sale to numbers
sales_df["Total_Sale"] = pd.to_numeric(
    sales_df["Total_Sale"]
    .astype(str)
    .str.replace("$", "", regex=False)
    .str.replace(",", "", regex=False),
    errors="coerce"
)

# Summarise sales performance by product
product_summary = (
    sales_df.groupby("Product")
    .agg(
        Total_Sales=("Total_Sale", "sum"),
        Average_Sale=("Total_Sale", "mean"),
        Transactions=("Total_Sale", "count")
    )
    .sort_values("Total_Sales", ascending=False)
    .round(2)
)

display(product_summary)

                             Total_Sales  Average_Sale  Transactions
Product
Laptop - Business Grade         22788.00      22788.00             1
Whiteboard - Interactive         7596.00       7596.00             1
Monitor - 27 inch                7002.00       7002.00             1
Router - Business Grade          4998.75       4998.75             1
Business Analytics Software      4998.00       4998.00             1
Projector - 4K Business          4799.70       4799.70             1
Standing Desk                    4792.00       4792.00             1
Office Chair - Ergonomic         4492.50       4492.50             1
Conference Table                 3750.00       3750.00             1
Coffee Machine - Commercial      3599.80       3599.80             1
Desk Lamp - LED                  3597.75       3597.75             1
Printer - Multifunction          3592.00       3592.00             1
Keyboard - Wireless              3132.50       3132.50             1
Filing Cabinet                   2994.00       2994.00             1
Security Camera System           2598.00       2598.00             1
Air Purifier - Office            2093.00       2093.00             1
Shredder - Industrial            1995.00       1995.00             1
Office Phone System              1895.00       1895.00             1
UPS Battery Backup               1619.55       1619.55             1
Mouse - Ergonomic                1608.25       1608.25             1

**Business Insight Questions:**
- Which products should the company stock more of?

Based on this dataset, the company could consider keeping enough stock of Laptop - Business Grade, which had the highest recorded sales value ($22,788). However, each product appears in only one transaction, so this data alone is not enough to confirm which products customers buy most often.

- Are high-price items selling well, or is volume more important?

The highest-value sale was for the laptop, suggesting that a high-price item can make a large contribution to revenue. But the dataset does not show repeat purchase volume for any product—each product has one transaction—so we cannot determine whether high-price items or higher sales volume is more important.

- What would you recommend to the inventory manager?    
Use these results as an initial guide, but avoid making major stock decisions from this small dataset alone. Track product sales over a longer period, including quantities sold, stock levels, and repeat transactions. Then prioritize products that show consistently strong demand while keeping high-priced items in stock at a level that limits the risk of unsold inventory.
---

## Practice Exercise 1.3: Sales Rep Performance

::: {.callout-tip}
## Management Challenge

Your sales manager wants to recognize top performers and identify who might need additional training.

**Your Task**: Create prompts that help analyze:
1. Which sales reps are generating the most revenue?
2. Who has the highest average sale amounts?
3. Are there regional patterns in rep performance?
4. Format results suitable for a performance review meeting
:::

**Your Approach:**

# Try different AI prompts and compare results

# Prompt1：Using the sales_df DataFrame, analyse sales representative performance. Calculate each sales representative's total revenue, average sale amount, and number of transactions. Sort the results by total revenue from highest to lowest. Also compare performance by region if the Sales_Rep and Region columns are available. Format the results clearly for a performance review meeting, and explain any limitations of the data.

In [10]:

import pandas as pd

# Convert Total_Sale to numbers in case it contains dollar signs or commas
sales_df["Total_Sale"] = pd.to_numeric(
    sales_df["Total_Sale"]
    .astype(str)
    .str.replace("$", "", regex=False)
    .str.replace(",", "", regex=False),
    errors="coerce"
)

# Summarise performance for each sales representative
rep_summary = (
    sales_df.groupby("Sales_Rep")
    .agg(
        Total_Revenue=("Total_Sale", "sum"),
        Average_Sale=("Total_Sale", "mean"),
        Transactions=("Total_Sale", "count")
    )
    .sort_values("Total_Revenue", ascending=False)
    .round(2)
)

print("Sales Rep Performance:")
display(rep_summary)

# Compare total revenue by region and sales representative
region_rep_summary = (
    sales_df.groupby(["Region", "Sales_Rep"])
    .agg(
        Total_Revenue=("Total_Sale", "sum"),
        Transactions=("Total_Sale", "count")
    )
    .sort_values("Total_Revenue", ascending=False)
    .round(2)
)

print("Performance by Region and Sales Rep:")
display(region_rep_summary)

Sales Rep Performance:

               Total_Revenue  Average_Sale  Transactions
Sales_Rep
David Kumar         32506.50       8126.62             4
Michael Wong        21085.50       5271.38             4
Sarah Chen          18396.25       4599.06             4
Emma Thompson       11904.30       2976.08             4
Lisa Park           10049.25       2512.31             4

Performance by Region and Sales Rep:

                      Total_Revenue  Transactions
Region Sales_Rep
NSW    David Kumar         32506.50             4
VIC    Michael Wong        21085.50             4
NSW    Sarah Chen          18396.25             4
QLD    Emma Thompson       11904.30             4
WA     Lisa Park           10049.25             4

# Prompt2：Analyse sales rep performance using total revenue, average sale amount, and transaction count. Rank the sales reps by total revenue. Then explain the top performer and any limitations of the data in simple language.

In [11]:
import pandas as pd

# Make sure Total_Sale contains numbers
sales_df["Total_Sale"] = pd.to_numeric(
    sales_df["Total_Sale"]
    .astype(str)
    .str.replace("$", "", regex=False)
    .str.replace(",", "", regex=False),
    errors="coerce"
)

# Summarise performance by sales representative
rep_summary = (
    sales_df.groupby("Sales_Rep")
    .agg(
        Total_Revenue=("Total_Sale", "sum"),
        Average_Sale_Amount=("Total_Sale", "mean"),
        Transaction_Count=("Total_Sale", "count"),
        Region=("Region", "first")
    )
    .sort_values("Total_Revenue", ascending=False)
    .round(2)
)

print("Sales representatives ranked by total revenue:")
display(rep_summary)

# Explain the top performer and a limitation
top_rep = rep_summary.index[0]
top_revenue = rep_summary.iloc[0]["Total_Revenue"]
top_average = rep_summary.iloc[0]["Average_Sale_Amount"]
top_transactions = int(rep_summary.iloc[0]["Transaction_Count"])
top_region = rep_summary.iloc[0]["Region"]

print(
    f"\n{top_rep} is the top performer in this dataset. "
    f"They are based in {top_region}, with total revenue of "
    f"${top_revenue:,.2f}, an average sale amount of "
    f"${top_average:,.2f}, and {top_transactions} transactions."
)

print(
    "\nLimitation: This dataset has only a small number of transactions "
    "for each representative, so it may not show their performance "
    "over a longer period."
)

Sales representatives ranked by total revenue:

               Total_Revenue  Average_Sale_Amount  Transaction_Count Region
Sales_Rep
David Kumar         32506.50              8126.62                  4    NSW
Michael Wong        21085.50              5271.38                  4    VIC
Sarah Chen          18396.25              4599.06                  4    NSW
Emma Thompson       11904.30              2976.08                  4    QLD
Lisa Park           10049.25              2512.31                  4     WA

David Kumar is the top performer in this dataset. They are based in NSW, with total revenue of $32,506.50, an average sale amount of $8,126.62, and 4 transactions.

Limitation: This dataset has only a small number of transactions for each representative, so it may not show their performance over a longer period.

# Document which prompts work best

# The prompt that clearly requested total revenue, average sale amount, transaction count, and ranking by total revenue worked best. It produced an organised comparison that was easy to use in a performance review. However, the dataset contains only four transactions per sales representative, so the results should be treated as an initial comparison rather than a complete measure of performance.

In [ ]:
#Analyse sales rep performance using total revenue, average sale amount, and transaction count. Rank the sales reps by total revenue. Then explain the top performer and any limitations of the data in simple language.

---

# Exercise Set 2: Financial Transaction Patterns 💳

## Advanced Analysis Practice

Using the original transactions data, practice more sophisticated AI collaboration.

In [7]:
# Reload transaction data for advanced practice
transactions_df = pd.read_csv("/content/transactions.csv")
print("Transaction data loaded for advanced practice")

Transaction data loaded for advanced practice

## Practice Exercise 2.1: Spending Trend Analysis

::: {.callout-tip}
## Business Context

You're helping a friend understand their spending habits over time.

**Challenge**: Ask AI to help you:
1. Convert dates to datetime format
2. Analyze spending trends by day of week
3. Identify if spending has increased over time
4. Spot any unusual spending patterns

**Focus**: Practice asking AI to explain any complex date handling code it provides.
:::

**Your Analysis:**

In [ ]:
# Your AI collaboration for time-based analysis

In [8]:
import pandas as pd

# Display the transaction data column names
print("Columns in the transaction data:")
print(transactions_df.columns.tolist())

# Try to identify the date and amount columns
date_candidates = [
    "Date", "Transaction_Date", "TransactionDate",
    "date", "transaction_date"
]
amount_candidates = [
    "Amount", "Transaction_Amount", "TransactionAmount",
    "amount", "transaction_amount"
]

date_col = next(
    (col for col in date_candidates if col in transactions_df.columns),
    None
)
amount_col = next(
    (col for col in amount_candidates if col in transactions_df.columns),
    None
)

# If common names were not found, search column names for keywords
if date_col is None:
    date_col = next(
        (col for col in transactions_df.columns if "date" in col.lower()),
        None
    )

if amount_col is None:
    amount_col = next(
        (
            col for col in transactions_df.columns
            if any(word in col.lower() for word in ["amount", "spend", "value"])
        ),
        None
    )

# Check whether both columns were identified
if date_col is None or amount_col is None:
    print("\nCould not automatically identify the date and amount columns.")
    print("Check the column names displayed above.")
else:
    print(f"\nDate column: {date_col}")
    print(f"Amount column: {amount_col}")

    # Convert the date and amount columns to suitable formats
    transactions_df[date_col] = pd.to_datetime(
        transactions_df[date_col],
        errors="coerce"
    )

    transactions_df[amount_col] = pd.to_numeric(
        transactions_df[amount_col]
        .astype(str)
        .str.replace("$", "", regex=False)
        .str.replace(",", "", regex=False),
        errors="coerce"
    )

    # Remove rows with missing or invalid dates or amounts
    analysis_df = transactions_df.dropna(
        subset=[date_col, amount_col]
    ).copy()

    # Create day-of-week and month columns
    analysis_df["Day_of_Week"] = analysis_df[date_col].dt.day_name()
    analysis_df["Month"] = analysis_df[date_col].dt.to_period("M").astype(str)

    # Summarise spending by day of the week
    weekday_summary = (
        analysis_df.groupby("Day_of_Week")[amount_col]
        .agg(["sum", "mean", "count"])
        .rename(columns={
            "sum": "Total_Spending",
            "mean": "Average_Spending",
            "count": "Transactions"
        })
        .reindex([
            "Monday", "Tuesday", "Wednesday", "Thursday",
            "Friday", "Saturday", "Sunday"
        ])
        .round(2)
    )

    # Summarise spending by month to observe the trend over time
    monthly_summary = (
        analysis_df.groupby("Month")[amount_col]
        .agg(["sum", "mean", "count"])
        .rename(columns={
            "sum": "Total_Spending",
            "mean": "Average_Spending",
            "count": "Transactions"
        })
        .round(2)
    )

    # Identify unusually high transactions:
    # amounts greater than the mean plus two standard deviations
    average_amount = analysis_df[amount_col].mean()
    standard_deviation = analysis_df[amount_col].std()

    unusual = analysis_df[
        analysis_df[amount_col] > average_amount + 2 * standard_deviation
    ].sort_values(amount_col, ascending=False)

    print("\nSpending by day of the week:")
    display(weekday_summary)

    print("\nSpending by month:")
    display(monthly_summary)

    print("\nUnusually high transactions:")
    if unusual.empty:
        print("No unusually high transactions were found using this rule.")
    else:
        display(unusual[[date_col, amount_col, "Day_of_Week"]])

    # Print a simple summary of the results
    print("\nSimple summary:")

    if not monthly_summary.empty:
        first_month = monthly_summary.iloc[0]["Total_Spending"]
        last_month = monthly_summary.iloc[-1]["Total_Spending"]

        if last_month > first_month:
            print(
                "Total spending was higher in the last month "
                "than in the first month."
            )
        elif last_month < first_month:
            print(
                "Total spending was lower in the last month "
                "than in the first month."
            )
        else:
            print(
                "Total spending was the same in the first and last months."
            )

    if not weekday_summary["Total_Spending"].dropna().empty:
        highest_day = weekday_summary["Total_Spending"].idxmax()
        print(f"The highest total spending was on {highest_day}.")

    print(
        "Limitation: This analysis only covers the transactions in this "
        "dataset. It may not represent spending habits outside the "
        "recorded period."
    )

Columns in the transaction data:
['Date', 'Amount', 'Category', 'Description']

Date column: Date
Amount column: Amount

Spending by day of the week:

             Total_Spending  Average_Spending  Transactions
Day_of_Week
Monday               298.00             99.33             3
Tuesday              -10.70             -3.57             3
Wednesday            180.00             90.00             2
Thursday              90.35             30.12             3
Friday                67.30             22.43             3
Saturday             139.15             46.38             3
Sunday               109.20             36.40             3

Spending by month:

         Total_Spending  Average_Spending  Transactions
Month
2024-08           873.3             43.66            20

Unusually high transactions:

         Date  Amount Day_of_Week
11 2024-08-12   156.0      Monday

Simple summary:
Total spending was the same in the first and last months.
The highest total spending was on Monday.
Limitation: This analysis only covers the transactions in this dataset. It may not represent spending habits outside the recorded period.

The analysis shows that total spending varied across the days of the week. Tuesday had a negative total spending amount of -10.70. This may be due to a refund or a reversed transaction recorded as a negative value, so it should not be treated as normal spending without checking the transaction details. The dataset only covers August 2024, so it is not enough to determine whether spending increased over time or to identify longer-term patterns.

## Practice Exercise 2.2: Budget Category Analysis

::: {.callout-tip}
## Personal Finance Scenario

Someone wants to set a realistic monthly budget based on their spending history.

**Challenge**: Use AI to help:
1. Calculate average monthly spending by category
2. Identify categories with high variation (inconsistent spending)
3. Suggest realistic budget amounts for each category
4. Find categories where spending might be reduced

**Advanced**: Ask AI to explain the statistical concepts it uses.
:::

**Your Budget Analysis:**

In [10]:
# AI-assisted budget recommendation code

import pandas as pd

# Use the existing transaction data
budget_df = transactions_df.copy()

# Convert the amount column to numeric values
budget_df["Amount"] = pd.to_numeric(
    budget_df["Amount"]
        .astype(str)
        .str.replace("$", "", regex=False)
        .str.replace(",", "", regex=False),
    errors="coerce"
)

# Remove rows with missing category or amount
budget_df = budget_df.dropna(subset=["Category", "Amount"]).copy()

# Summarize spending by category
category_summary = (
    budget_df.groupby("Category")["Amount"]
    .agg(
        Total_Spending="sum",
        Average_Transaction="mean",
        Transactions="count",
        Spending_Std="std"
    )
    .fillna({"Spending_Std": 0})
    .sort_values("Total_Spending", ascending=False)
)

print("Spending by category:")
display(category_summary)

# Calculate category shares using positive spending only
positive_spending = budget_df.loc[budget_df["Amount"] > 0].copy()
total_positive_spending = positive_spending["Amount"].sum()

if total_positive_spending > 0:
    category_share = (
        positive_spending.groupby("Category")["Amount"].sum()
        / total_positive_spending * 100
    ).sort_values(ascending=False)

    print("\nShare of positive spending by category (%):")
    display(category_share.round(1))

# Identify categories with the highest and lowest total amounts
if not category_summary.empty:
    highest_category = category_summary["Total_Spending"].idxmax()
    lowest_category = category_summary["Total_Spending"].idxmin()

    print(f"\nHighest total category: {highest_category}")
    print(f"Lowest total category: {lowest_category}")

print(
    "\nLimitation: The dataset covers only one month, "
    "so it cannot show reliable monthly averages or long-term variation."
)

Spending by category:

               Total_Spending  Average_Transaction  Transactions  Spending_Std
Category
Groceries              394.70            98.675000             4     49.049184
Entertainment          206.95            68.983333             3     40.767031
Dining                 113.90            56.950000             2     39.668690
Transport               89.50            29.833333             3     16.660832
Utilities               67.80            67.800000             1      0.000000
Coffee                  37.95             7.590000             5      5.053266
Refund                 -37.50           -18.750000             2      8.838835

Share of positive spending by category (%):

Category
Groceries        43.3
Entertainment    22.7
Dining           12.5
Transport         9.8
Utilities         7.4
Coffee            4.2
Name: Amount, dtype: float64

Highest total category: Groceries
Lowest total category: Refund

Limitation: The dataset covers only one month, so it cannot show reliable monthly averages or long-term variation.

Budget Category Analysis: Groceries had the highest spending, with a total of 394 dollars and 70 cents. This was 43.3 percent of positive spending. Entertainment was second, at 206 dollars and 95 cents, or 22.7 percent. Dining was third, at 113 dollars and 90 cents, or 12.5 percent. Groceries and entertainment had the largest variation in transaction amounts. Their standard deviations were about 49.05 and 40.77, respectively. This suggests that spending in these categories was less consistent during the recorded month.

Based on this one-month record, a starting monthly budget could be approximately:

Groceries: 435 dollars
Entertainment: 230 dollars
Dining: 125 dollars
Transport: 100 dollars
Utilities: 75 dollars
Coffee: 42 dollars
These amounts are slightly above the recorded spending totals to allow some flexibility. To reduce spending, the person could first review entertainment and dining purchases, while keeping track of grocery spending because it is the largest category.

Refunds totalled negative 37.50 dollars and should be treated separately from ordinary spending. This dataset covers only August 2024, so these budget amounts are initial estimates, not reliable long-term averages. More months of data are needed to confirm usual spending and variation.

---

# Exercise Set 3: AI Critique Practice 🤔

## Common AI Code Issues

Below are examples of AI-generated code with issues. Practice your critique skills!

### Critique Exercise 1: Overly Complex Code

```python
# AI generated this code - what's wrong with it?
import pandas as pd
import numpy as np
from datetime import datetime

def complex_analysis(data):
    result = data.groupby([pd.Grouper(key='Date', freq='M'), 'Category']).agg({
        'Amount': [lambda x: pd.to_numeric(x.str.replace('$', ''), errors='coerce').sum(),
                   lambda x: pd.to_numeric(x.str.replace('$', ''), errors='coerce').mean(),
                   lambda x: pd.to_numeric(x.str.replace('$', ''), errors='coerce').std()]
    }).reset_index()
    
    result.columns = ['_'.join(col).strip() for col in result.columns.values]
    return result.fillna(0).round(2)

# Complex usage
df['Date'] = pd.to_datetime(df['Date'])
complex_result = complex_analysis(transactions_df)
print(complex_result.head())
```

**Your Critique:**

::: {.callout-warning}
## Issues to Identify

1. What makes this code hard to understand?
2. What would you ask AI to simplify?
3. How would you request a clearer version?

**Write your critique prompt:**
:::

```
Please improve this code for a business audience. Use clear column names and explain what the results show. Present the totals in a well-formatted table, sorted from highest to lowest spending. Include a brief, practical business insight and explain any limitations of the data. Do not make claims that are not supported by the data.

```

### Critique Exercise 2: Poor Business Context

```python
# AI code that works but lacks business insight
df_grouped = df.groupby('cat')['amt'].sum().sort_values()
print(df_grouped)
```

**Problems:**
- Unclear column references
- No business explanation
- Poor formatting
- No context for results

**Your Improvement Prompt:**
```
[How would you ask AI to make this more business-appropriate?]
Please improve this code for a business audience. Use clear column names and explain what the results show. Present the totals in a well-formatted table, sorted from highest to lowest spending. Include a brief, practical business insight and explain any limitations of the data. Do not make claims that are not supported by the data.
```

---

# Exercise Set 4: Real-World Business Scenarios 🏢

## Scenario 1: Retail Store Analysis

::: {.callout-note}
## Business Context

You're analyzing sales data for a small retail chain. They want to know:
- Which stores need more inventory
- What products to discontinue
- When to schedule promotional campaigns
- How to allocate sales staff

**Data**: Use the sales_data.csv but imagine it represents different store locations instead of regions.
:::

**Your Business Analysis:**

In [16]:
# Practice comprehensive business analysis with AI assistance


import pandas as pd

# Load the sales data
sales_df = pd.read_csv("/content/sales_data.csv")

# Convert currency-formatted values into numbers
for column in ["Quantity", "Unit_Price", "Total_Sale"]:
    sales_df[column] = pd.to_numeric(
        sales_df[column]
        .astype(str)
        .str.replace(r"[$,]", "", regex=True),
        errors="coerce"
    )

# Remove rows with missing values needed for this analysis
analysis_df = sales_df.dropna(
    subset=["Region", "Product", "Quantity", "Total_Sale"]
).copy()

# Treat each region as a store location
store_summary = (
    analysis_df.groupby("Region")
    .agg(
        Total_Sales=("Total_Sale", "sum"),
        Average_Sale=("Total_Sale", "mean"),
        Transaction_Count=("Total_Sale", "count")
    )
    .sort_values("Total_Sales", ascending=False)
    .round(2)
)

# Summarise sales and quantities by product
product_summary = (
    analysis_df.groupby("Product")
    .agg(
        Total_Sales=("Total_Sale", "sum"),
        Total_Quantity=("Quantity", "sum"),
        Transaction_Count=("Product", "count")
    )
    .sort_values("Total_Sales", ascending=False)
    .round(2)
)

print("Store performance (regions treated as store locations):")
display(store_summary)

print("\nProduct performance:")
display(product_summary)

# Focus on actionable insights, not just data summaries

Store performance (regions treated as store locations):

        Total_Sales  Average_Sale  Transaction_Count
Region
NSW        50902.75       6362.84                  8
VIC        21085.50       5271.38                  4
QLD        11904.30       2976.08                  4
WA         10049.25       2512.31                  4

Product performance:

                             Total_Sales  Total_Quantity  Transaction_Count
Product
Laptop - Business Grade         22788.00              12                  1
Whiteboard - Interactive         7596.00               4                  1
Monitor - 27 inch                7002.00              18                  1
Router - Business Grade          4998.75              25                  1
Business Analytics Software      4998.00               2                  1
Projector - 4K Business          4799.70               6                  1
Standing Desk                    4792.00               8                  1
Office Chair - Ergonomic         4492.50              15                  1
Conference Table                 3750.00               3                  1
Coffee Machine - Commercial      3599.80               4                  1
Desk Lamp - LED                  3597.75              45                  1
Printer - Multifunction          3592.00               8                  1
Keyboard - Wireless              3132.50              35                  1
Filing Cabinet                   2994.00              12                  1
Security Camera System           2598.00               2                  1
Air Purifier - Office            2093.00               7                  1
Shredder - Industrial            1995.00               5                  1
Office Phone System              1895.00              10                  1
UPS Battery Backup               1619.55               9                  1
Mouse - Ergonomic                1608.25              35                  1

## Scenario 2: Personal Finance Coaching

::: {.callout-note}
## Business Context

You're building a personal finance app feature that provides spending advice.

**Challenge**: Use AI to create code that:
1. Identifies spending categories that are above typical percentages
2. Suggests specific areas for potential savings
3. Provides encouraging feedback for good spending habits
4. Formats advice in a user-friendly way
:::

**Your Coaching Algorithm:**

In [22]:
# AI-assisted personal finance advice generationimport os
import re
import sys
import pandas as pd

# Load the transactions file if it is not already loaded.
if "transactions_df" not in globals() or not isinstance(
    globals().get("transactions_df"), pd.DataFrame
):
    file_path = "/content/transactions.csv"
    if not os.path.exists(file_path):
        print(f"Could not find {file_path}. Upload transactions.csv to Colab and try again.")
        raise FileNotFoundError(file_path)
    transactions_df = pd.read_csv(file_path)

# Match likely column names, allowing common spelling and formatting variations.
def normalize_name(name):
    return re.sub(r"[^a-z0-9]", "", str(name).lower())

columns_by_normalized_name = {
    normalize_name(column): column for column in transactions_df.columns
}

def find_column(candidates, keywords):
    for candidate in candidates:
        match = columns_by_normalized_name.get(normalize_name(candidate))
        if match is not None:
            return match

    for column in transactions_df.columns:
        normalized = normalize_name(column)
        if any(keyword in normalized for keyword in keywords):
            return column
    return None

category_col = find_column(
    ["category", "spending_category", "expense_category", "type", "description"],
    ["category", "expense", "merchant", "description", "type"],
)
amount_col = find_column(
    ["amount", "transaction_amount", "debit", "spend", "value", "cost"],
    ["amount", "debit", "spend", "cost", "value"],
)
date_col = find_column(
    ["date", "transaction_date", "posted_date", "datetime", "timestamp"],
    ["date", "time"],
)

missing_columns = []
if category_col is None:
    missing_columns.append("category")
if amount_col is None:
    missing_columns.append("amount")
if date_col is None:
    missing_columns.append("date")

if missing_columns:
    print("I could not identify the required column(s): " + ", ".join(missing_columns))
    print("Available columns:", list(transactions_df.columns))
    raise SystemExit("Please check your column names or update the column matching rules.")

# Convert amounts such as "$1,234.56" and "($20.00)" to numbers.
amount_text = transactions_df[amount_col].astype(str).str.strip()
parentheses_are_negative = amount_text.str.match(r"^\(.*\)$")
clean_amount = (
    amount_text
    .str.replace(r"[$£€¥,\s]", "", regex=True)
    .str.replace(r"^\((.*)\)$", r"-\1", regex=True)
    .str.replace(r"[^0-9.+\-]", "", regex=True)
)
transactions_df["_clean_amount"] = pd.to_numeric(clean_amount, errors="coerce")
transactions_df.loc[parentheses_are_negative, "_clean_amount"] = (
    -transactions_df.loc[parentheses_are_negative, "_clean_amount"].abs()
)

# Parse dates and report the period represented by usable records.
transactions_df["_clean_date"] = pd.to_datetime(
    transactions_df[date_col], errors="coerce"
)
valid_dates = transactions_df["_clean_date"].dropna()

print("PERSONAL FINANCE SPENDING CHECK")
print("-" * 38)
if not valid_dates.empty:
    print(
        "Data period:",
        f"{valid_dates.min().date()} to {valid_dates.max().date()}",
    )
else:
    print("Data period: dates could not be parsed.")

# Keep categorized positive amounts for spending totals.
analysis_df = transactions_df[
    transactions_df["_clean_amount"].notna()
    & transactions_df[category_col].notna()
    & (transactions_df["_clean_amount"] > 0)
].copy()

if analysis_df.empty:
    print("\nNo positive spending amounts with categories were found.")
    print("Check that purchases are represented as positive amounts in the file.")
    raise SystemExit

analysis_df["_category"] = analysis_df[category_col].astype(str).str.strip()
analysis_df = analysis_df[analysis_df["_category"] != ""]

category_spending = analysis_df.groupby("_category")["_clean_amount"].sum()
total_spending = category_spending.sum()

if total_spending <= 0:
    print("\nThere is no positive spending to summarize.")
    raise SystemExit

category_percentages = category_spending / total_spending * 100

# Illustrative examples only; adjust these percentages to fit your circumstances.
# The example shares add up to 100%.
example_benchmarks = {
    "housing": 30,
    "rent": 30,
    "food": 15,
    "groceries": 15,
    "transportation": 10,
    "transport": 10,
    "utilities": 8,
    "health": 7,
    "healthcare": 7,
    "entertainment": 10,
    "dining": 5,
    "shopping": 5,
    "savings": 10,
}

def benchmark_for(category):
    key = normalize_name(category)
    for benchmark_name, percentage in example_benchmarks.items():
        if key == normalize_name(benchmark_name):
            return percentage
    return None

print(f"\nPositive spending found: {total_spending:,.2f}")
print("\nCategory comparison")
print("(Benchmarks are illustrative examples, not personal recommendations.)")
print("-" * 72)
print(f"{'Category':<24} {'Spent':>12} {'Share':>10} {'Example':>10}  Note")
print("-" * 72)

for category, spent in category_spending.sort_values(ascending=False).items():
    share = category_percentages[category]
    benchmark = benchmark_for(category)

    if benchmark is None:
        note = "No matching example benchmark"
        benchmark_text = "—"
    elif share > benchmark:
        note = "Above example"
        benchmark_text = f"{benchmark:.0f}%"
    else:
        note = "Within/below example"
        benchmark_text = f"{benchmark:.0f}%"

    print(
        f"{category[:23]:<24} {spent:>12,.2f} "
        f"{share:>9.1f}% {benchmark_text:>10}  {note}"
    )

print("\nPotential next steps")
above_categories = [
    (category, category_percentages[category], benchmark_for(category))
    for category in category_spending.index
    if benchmark_for(category) is not None
    and category_percentages[category] > benchmark_for(category)
]

if above_categories:
    for category, share, benchmark in sorted(
        above_categories, key=lambda item: item[1] - item[2], reverse=True
    ):
        category_key = normalize_name(category)
        if any(word in category_key for word in ["dining", "restaurant", "food"]):
            action = "Try planning a few lower-cost meals or setting a weekly dining limit."
        elif any(word in category_key for word in ["shopping", "retail"]):
            action = "Consider a 24-hour pause before non-essential purchases."
        elif any(word in category_key for word in ["transport", "travel", "fuel"]):
            action = "Compare transit, carpool, or trip-planning options where practical."
        elif any(word in category_key for word in ["entertainment", "subscription"]):
            action = "Review recurring subscriptions and keep the ones you use most."
        elif any(word in category_key for word in ["housing", "rent"]):
            action = "Review recurring housing costs and possible lower-cost options when feasible."
        else:
            action = "Review recent transactions and look for one manageable cost to reduce."

        print(
            f"- {category}: {share:.1f}% of spending, above the "
            f"{benchmark:.0f}% example. {action}"
        )
else:
    print("No categories matched an example benchmark above its illustrative percentage.")

print("\nEncouragement")
within_or_below = [
    category
    for category in category_spending.index
    if benchmark_for(category) is not None
    and category_percentages[category] <= benchmark_for(category)
]
if within_or_below:
    print(
        "Nice work: these matched categories are within or below their examples: "
        + ", ".join(within_or_below)
        + ". Keep focusing on choices that fit your needs."
    )
else:
    print(
        "Keep going: a category comparison is only a starting point. "
        "Small, realistic changes can help you understand your spending."
    )

print(
    "\nImportant: Results reflect only the transactions and dates in this file. "
    "The percentages are limited illustrative examples, not a universal budget, "
    "and categories without a matching example cannot be compared. "
    "This output is for learning and is not financial advice."
)

PERSONAL FINANCE SPENDING CHECK
--------------------------------------
Data period: 2024-08-01 to 2024-08-20

Positive spending found: 910.80

Category comparison
(Benchmarks are illustrative examples, not personal recommendations.)
------------------------------------------------------------------------
Category                        Spent      Share    Example  Note
------------------------------------------------------------------------
Groceries                      394.70      43.3%        15%  Above example
Entertainment                  206.95      22.7%        10%  Above example
Dining                         113.90      12.5%         5%  Above example
Transport                       89.50       9.8%        10%  Within/below example
Utilities                       67.80       7.4%         8%  Within/below example
Coffee                          37.95       4.2%          —  No matching example benchmark

Potential next steps
- Groceries: 43.3% of spending, above the 15% example. Review recent transactions and look for one manageable cost to reduce.
- Entertainment: 22.7% of spending, above the 10% example. Review recurring subscriptions and keep the ones you use most.
- Dining: 12.5% of spending, above the 5% example. Try planning a few lower-cost meals or setting a weekly dining limit.

Encouragement
Nice work: these matched categories are within or below their examples: Transport, Utilities. Keep focusing on choices that fit your needs.

Important: Results reflect only the transactions and dates in this file. The percentages are limited illustrative examples, not a universal budget, and categories without a matching example cannot be compared. This output is for learning and is not financial advice.

---

# Self-Assessment Checklist ✅

After completing these exercises, evaluate your AI collaboration skills:

## AI Prompting Skills
- ☐ I can write prompts that include business context
- ☐ I specify desired output format and structure  
- ☐ I ask follow-up questions to improve AI responses
- ☐ I can request explanations of complex code

## Code Critique Skills
- ☐ I can identify when AI code is too complex
- ☐ I recognize when variable names need improvement
- ☐ I spot when business context is missing
- ☐ I ask for clearer, more maintainable solutions

## Business Application Skills  
- ☐ I connect data analysis to real business decisions
- ☐ I can explain technical results in business terms
- ☐ I consider edge cases and data quality issues
- ☐ I format results for business presentation

## Learning Documentation
- ☐ I document what I learned from each AI interaction
- ☐ I record effective prompts for future use
- ☐ I note when AI explanations helped my understanding
- ☐ I reflect on how to improve my collaboration

---

# Reflection Questions 🤔

Before finishing your practice session, consider:

1. **Which AI interactions were most helpful for your learning?**
 I learned that clear prompts work better when I include context, the desired output, and a request for a simple explanation. This helped with both sales data and personal finance tasks.

2. **What types of prompts got you the best code explanations?**
 I improved prompts through follow-up questions and critique when the output or code did not fit what I needed. I also noticed issues such as missing files and mismatched column names.

3. **When did you successfully critique and improve AI responses?**
 I checked the code and its outputs instead of assuming they were correct. This helped me notice that some benchmarks were illustrative and that the data covered only a limited period.

4. **How has your confidence with business data analysis changed?**
 My confidence using AI and Colab improved, but I still need to check the code, data, and results carefully. AI can be helpful, but its output is not automatically reliable.

5. **What AI collaboration strategies will you use in your assignment?**
 For future assignments, I will document my prompts, test the code, check the data and its limitations, and explain the results honestly.

---

# Next Steps 🚀

**For Your Assignment:**
- Apply these prompting techniques to your Smart Finance Assistant
- Use the critique skills to ensure your code is business-appropriate
- Document successful AI interactions in your Developer's Diary
- Build on the confidence you've gained with these practice exercises

**Remember**: You're not trying to become a pandas expert overnight. You're becoming skilled at directing AI to solve business problems efficiently and effectively.

**Great practice work! These skills will serve you well throughout your Smart Finance Assistant project and in your future career! 🎉**

Developer’s Diary

I recorded the main AI interactions from the Week 10 practice, organized by exercise. These notes summarize the prompts and work; they are not a verbatim record of every prompt.

Set 1: Regional Sales and Product Analysis

Regional sales





What I asked AI: I asked for help writing code to compare sales across regions.



What AI helped with: AI suggested code to group the data by region and summarize sales.



My checks or changes: I checked that the CSV uploaded correctly, the file path was right, and the column names in the code matched the data.



What I learned: I learned to check the file and column names before running analysis.

Top-performing products





What I asked AI: I asked how to find which products performed best.



What AI helped with: AI helped summarize sales by product and compare the results.



My checks or changes: I checked the product and sales columns and reviewed whether the summary matched the dataset.



What I learned: I learned that the answer depends on which measure of performance is used.

Sales-representative comparison





What I asked AI: I asked for help comparing sales representatives.



What AI helped with: AI suggested grouping and comparing sales by representative.



My checks or changes: I checked that the relevant column was available and that the comparison used the intended sales measure.



What I learned: I learned to confirm what a comparison represents before explaining it.

Exercise 1.3: Trying different prompts





What I asked AI: I tried different prompts for the same exercise.



What AI helped with: AI produced different responses to compare.



My checks or changes: I compared the outputs and checked them against the task and available data.



What I learned: Prompt wording can affect an answer, so I should review the output rather than choose one automatically.

Set 2: Spending Analysis

Spending trend analysis





What I asked AI: I asked for help analyzing spending trends from the transactions CSV.



What AI helped with: AI suggested ways to summarize spending over time.



My checks or changes: I checked the upload, path, and column names. I also considered that the data covered only a limited time period and checked how negative amounts were represented before interpreting them.



What I learned: I should explain the limits of the data and verify what positive and negative amounts mean.

Budget category analysis





What I asked AI: I asked for help summarizing spending by budget category.



What AI helped with: AI suggested grouping transactions by category and comparing totals.



My checks or changes: I checked the category and amount columns, then reviewed whether the results made sense given the data.



What I learned: Correct column names and careful interpretation matter when using AI-generated code.

Set 3: Critique and Improvement Exercises

Critiquing code and analysis





What I asked AI: I used critique prompts to review code and the analysis.



What AI helped with: AI pointed out areas that could be unclear or complex.



My checks or changes: I checked whether the critique applied to the actual code and data. I also considered whether important business context was missing.



What I learned: A critique is useful to consider, but I need to judge it against the task.

Asking for improvements





What I asked AI: I asked for clearer improvements to the code or explanation.



What AI helped with: AI suggested changes intended to make the work easier to understand.



My checks or changes: I reviewed the suggestions and focused on changes that fit the exercise.



What I learned: Asking for clear, specific improvements can make AI feedback more useful.

Scenario 1: Retail-Store Analysis





What I asked AI: I asked how the sales analysis could be considered in a retail-store scenario.



What AI helped with: AI helped connect the exercise to comparing sales by region.



My checks or changes: I treated region as a practice assumption. The dataset did not contain actual store names, so I did not describe the results as a comparison of named stores.



What I learned: I should distinguish between information in the dataset and assumptions used for practice.

Scenario 2: Personal-Finance Spending Coach





What I asked AI: I asked about using spending data in a personal-finance coaching algorithm.



What AI helped with: AI helped frame ways to summarize spending and consider budget categories.



My checks or changes: I checked the output against the available data. I treated example benchmarks as illustrative, not as personal financial advice.



What I learned: A useful scenario still needs careful checks, and general examples should not be presented as personal recommendations.

Overall Reflection

This practice helped me learn to check AI-generated code, the uploaded data, and the meaning of the results. I need to confirm that paths and column names are correct, notice limits in the dataset, and avoid making claims the data cannot support. AI can help me explore and improve an analysis, but I am responsible for checking its suggestions.